workflows:
  react-native-bare-android:
    name: React Native Bare Android Build
    max_build_duration: 120
    environment:
      node: 18
      java: 17
      android_signing:
        - SMOKINGTIMER_RELEASE # 🔑 nome del keystore caricato nei Secure Files Codemagic
    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing dependencies..."
          npm ci

      - name: Clean Gradle
        script: |
          echo "🧹 Cleaning Gradle build..."
          cd android
          chmod +x gradlew  # ✅ fix permessi per gradlew
          ./gradlew clean

      - name: Build release APK
        script: |
          echo "🏗️ Building release APK..."
          cd android
          chmod +x gradlew  # ✅ fix permessi per gradlew
          ./gradlew assembleRelease --no-daemon --max-workers=2 --stacktrace --info --warning-mode all

      - name: Build release AAB
        script: |
          echo "📦 Building release AAB..."
          cd android
          chmod +x gradlew  # ✅ fix permessi per gradlew
          ./gradlew bundleRelease --no-daemon --max-workers=2 --stacktrace --info --warning-mode all

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - node_modules
